-- Create users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password VARCHAR2(100) NOT NULL
);

-- Create tickets table
CREATE TABLE tickets (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    event_name VARCHAR2(100),
    price NUMBER,
    user_id NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);